export default [
  { name: 'C1', selected: false, color: 'white' },
  { name: 'Csh1', selected: false, color: 'black' },
  { name: 'D1', selected: false, color: 'white' },
  { name: 'Dsh1', selected: false, color: 'black' },
  { name: 'E1', selected: false, color: 'white' },
  { name: 'F1', selected: false, color: 'white' },
  { name: 'Fsh1', selected: false, color: 'black' },
  { name: 'G1', selected: false, color: 'white' },
  { name: 'Gsh1', selected: false, color: 'black' },
  { name: 'A1', selected: false, color: 'white' },
  { name: 'Ash1', selected: false, color: 'black' },
  { name: 'B1', selected: false, color: 'white' },
  { name: 'C2', selected: false, color: 'white' },
  { name: 'Csh2', selected: false, color: 'black' },
  { name: 'D2', selected: false, color: 'white' },
  { name: 'Dsh2', selected: false, color: 'black' },
  { name: 'E2', selected: false, color: 'white' },
  { name: 'F2', selected: false, color: 'white' },
  { name: 'Fsh2', selected: false, color: 'black' },
  { name: 'G2', selected: false, color: 'white' },
  { name: 'Gsh2', selected: false, color: 'black' },
  { name: 'A2', selected: false, color: 'white' },
  { name: 'Ash2', selected: false, color: 'black' },
  { name: 'B2', selected: false, color: 'white' }
];
